# 開発環境用オーバーライド設定
# 使用方法: docker compose up -d で自動適用
# 本番環境では this ファイルは使用しない

services:
  api-server:
    # 開発用bind mount（即時反映）
    volumes:
      - ./services/api-server/public:/app/public
      - ./services/api-server/src:/app/src        # 開発用：srcも即時反映
    
    # 開発用環境変数
    environment:
      - NODE_ENV=development
      - DEV_ALLOW_INSECURE=1                      # 署名検証無効
      - LOG_LEVEL=DEBUG                           # デバッグログ有効
      - DEV_PUSH_DISABLE=1                        # LINE送信無効（ドライラン）
      - DEV_DEFAULT_USER_ID=${DEV_DEFAULT_USER_ID:-U45bc8ea2cb931b9ff43aa41559dbc7fc}
      - DEV_UNLINKED_USER_ID=${DEV_UNLINKED_USER_ID:-U_test_unlinked}
    
    # 依存関係を最小化（開発時問題回避）
    depends_on:
      - redis
      # caddyの依存を除去（開発時の起動問題を回避）
    
    # 開発用ポート直接公開（Caddy不要）
    ports:
      - "4000:4000"
  
  # 開発時はCaddyをprofile制御で無効化
  caddy:
    profiles: ["production"]  # 通常の開発では起動しない
    
  # linehookの依存関係も調整
  linehook:
    depends_on:
      - redis  # caddyへの依存を削除